version: '3'
services:
  web:
      image: nginx:latest
      ports:
          - "80:80"
      depends_on:
          - php
      volumes:
          - ./site.conf:/etc/nginx/conf.d/default.conf
  php:
      image: php:8.0-fpm
      volumes:
          - ./index.php:/app/index.php
          - ./flag.txt:/secret/flag.txt
          - ./user.db:/secret/user.db
